title: Seokhyun Moon
author: Seokhyun Moon
url: https://mseok.github.io
baseurl: ""
description: >-
  Ph.D. Candidate in KAIST Chemistry working on AI4Science models for drug
  discovery.
lang: en
timezone: Asia/Seoul
permalink: /:slug

theme_config:
  appearance: "light"
  appearance_toggle: true
  back_home_text: "home"
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_projects: false
  show_blog: true
  show_old_projects: false
  show_misc_list: false
  show_reading_time: true
  show_tags: true
  home:
    title_projects: Portfolio
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Old Projects

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Seokhyun Moon
